### ISSUE TITLE
SummonerPage: CurrentRank

### ISSUE THREAD

**Issue by JoaoPedroCarvalho** [LolStatsOrganization/LOLStats#10]
Be able to change the color of this based on rank

http://stackoverflow.com/questions/1777357/css-rule-based-on-content

**Comment by carvalho2707** [comment]
isto é para que?

**Comment by JoaoPedroCarvalho** [comment]
mudar a cor do rank na summoner page

**Comment by carvalho2707** [comment]
vou implementar

**Comment by carvalho2707** [comment]
Feito,tens de ir à summoner Page e escolher que cores queres para cada liga...
Eu pus até ao silver, o resto é dummy
