### ISSUE TITLE
add icons to about us

### ISSUE THREAD

**Issue by carvalho2707** [LolStatsOrganization/LOLStats#12]
Add icons for FB/linkin/twitter por baixo de cada um de nos.
e adicionar um icon com o cv???

**Comment by JoaoPedroCarvalho** [comment]
Will do

**Comment by carvalho2707** [comment]
Podias adicionar mais icons:
* Github icon
* jobcombinator icon
* e mais outros

**Comment by JoaoPedroCarvalho** [comment]
@carvalho2707 mete ai os links para os websites, assim que tiver tempo tento
