### ISSUE TITLE
Definir como será o filtro pela data

### ISSUE THREAD

**Issue by carvalho2707** [LolStatsOrganization/LOLStats#21]
Como vamos fazer o filtro das datas?
* começa e acaba onde?
* maximos
* etc

**Comment by JoaoPedroCarvalho** [comment]
o mínimo é a data do jogo mais antigo e o maximo o oposto.

**Comment by carvalho2707** [comment]
este issue nao tem sentido enquanto so virmos os mais recentes eheh.. vou por o filtro bloqueado mas com datas no formato que disseste..
ou entao vou filtrar à mesma mas so com os 10 jogoss

**Comment by JoaoPedroCarvalho** [comment]
faz isso
