### ISSUE TITLE
Tabs dos recent games

### ISSUE THREAD

**Issue by carvalho2707** [LolStatsOrganization/LOLStats#29]
as tabs nao estao a fazer muito sentido.. 
Acho que deviamos eliminar a dos 7 dias e mesmo assim custa-me a ter ali as outras.
Quando procuramos alguem podemos calcular 10 jogos (Recent riot) ou ranked(riot) ou o que estiver na bd.. por isso ter 30 dias e season acho que é muito tralha..
o que podemos por sem ser isto?

**Comment by JoaoPedroCarvalho** [comment]
eu acho que deviamos manter, é tipo um resumo das stats numa semana/mes/season
