### ISSUE TITLE
Procurar summoner

### ISSUE THREAD

**Issue by carvalho2707** [LolStatsOrganization/LOLStats#30]
O que acontece se ao procurarmos um summoner nao existir na riot/db??
Não temos ecra para isso certo?

**Comment by JoaoPedroCarvalho** [comment]
Se o summoner nao existir de maneira alguma é erro, posso criar uma pagina "index" modificada para aparecer a mensagem erro.
Se existir na nossae nao na deles temos que ir buscar
se existir nas 2 está tudo bem

**Comment by carvalho2707** [comment]
yap, tens de criar isso

**Comment by JoaoPedroCarvalho** [comment]
a pagina de erro vai ser a do teemo
