### ISSUE TITLE
Pagina itemset builder

### ISSUE THREAD

**Issue by carvalho2707** [LolStatsOrganization/LOLStats#34]
pensar no layout de uma pagina para criar item sets

**Comment by JoaoPedroCarvalho** [comment]
penso que seria algo muito do genero da do LoL Client, para ser possivel exportar/importar. Mas uma mistura desse com mobafire ou assim. Algo que filtrasse os items por Tier (os de tier 3 sao os items finais enquanto que os outros sao os basicos etc). Ou outros filtros interessantes

**Comment by carvalho2707** [comment]
vou procurar como é o do mobafire e depois tenta fazer alguma coisa
