### ISSUE TITLE
Pages to do? (Add more in comments)

### ISSUE THREAD

**Issue by JoaoPedroCarvalho** [LolStatsOrganization/LOLStats#4]
- [ ] Summoner Stats
- [ ] Match Stats
- [ ] Comparison
- [ ] League Status

**Comment by JoaoPedroCarvalho** [comment]
@carvalho2707 Vê e comenta (Já agora, que páginas queres nos links da homepage)

**Comment by carvalho2707** [comment]
Na pagina inicial ou temos uma pagina com um link para outra que tenha tipo as paginas todas( as principais) ou entao temos um link para cada principal

**Comment by JoaoPedroCarvalho** [comment]
neps, na inicial procuras pelo summoner e em baixo tens links extra (tal como o google)

**Comment by carvalho2707** [comment]
entao esse do summoner é a principal ya

**Comment by JoaoPedroCarvalho** [comment]
Não. a [summoner page](http://lolstats.webflow.io/summonerpage) é a que ainda tem pouco. 
A [principal](http://lolstats.webflow.io/) é a que só tem a caixa de texto e os links no footer.
