### ISSUE TITLE
add meta keywords to all pages

### ISSUE THREAD

**Issue by carvalho2707** [LolStatsOrganization/LOLStats#60]
Ficou : LoL, League of Legends, Tiago Carvalho, Joao Pedro Carvalho, summoner, summoner stats, stats, lol status, League, Legends, Match History, Riot

**Comment by carvalho2707** [comment]
League of Legends,Builds,Guides,Strategy,LoL,League of Legends Builds,LoL Guides,Champion Builds,Champion Guides,LoL Champions,League of Legends Champion Strategy,League of Legends Champion Builds

**Comment by carvalho2707** [comment]
Ficou : LoL, League of Legends, Tiago Carvalho, Joao Pedro Carvalho, summoner, summoner stats, stats, lol status


@JoaoPedroCarvalho mais alguma?

**Comment by JoaoPedroCarvalho** [comment]
vou assumir que quando metes (por exemplo) "league of legends" ele mete automaticamente "League". se nao tens de adicionar essas.

para alem disso: Match History, Riot

**Comment by carvalho2707** [comment]
done
