### ISSUE TITLE
create Sub title for LOLStats

### ISSUE THREAD

**Issue by carvalho2707** [LolStatsOrganization/LOLStats#68]
Precisamos de por um texto por baixo do titulo com uma descrição da app... se calhar pode ser igual À descriçao das meta tags

@JoaoPedroCarvalho  ajuda

**Comment by JoaoPedroCarvalho** [comment]
não é igual. "The best app to see your performance and analyze in-depth data about your matches"

**Comment by carvalho2707** [comment]
done, pode precisar de estilos
