### ISSUE TITLE
Stats to Add to compare and table compare

### ISSUE THREAD

**Issue by JoaoPedroCarvalho** [LolStatsOrganization/LOLStats#7]
- [ ] Blue/Red side winRate

**Comment by carvalho2707** [comment]
concordo

**Comment by carvalho2707** [comment]
date, time, length
role, champion, kda, cs, cs/min, side, result
kill contribution, kill contribution difference (from my lane opponent), death contribution, total CS difference
damage to champions (as a percentage of your team's damage) and damage to champions difference (again calculated based on percentage of team's damage)
kda and champion for all roles
league, division, LP and LP change
cs/min delta, cs/min diff delta, gold delta
bans
dragons/barons for both teams
first tower, blood, inhib, dragon, baron
wards placed, destroyed, vision wards bought, and the difference between your lane opponent
afks for both teams
